HMS/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.homepage, name='home'),

    path('', include('a_userauthapp.urls')),
    path('', include('b_hostels.urls')),

    path('hostel/<int:hostel_id>/', views.hostel_detail, name='hostel_detail'),
    path('select-room/<int:room_id>/', views.select_room, name='select_room'),
    path('submit-complaint/', views.submit_complaint, name='submit_complaint'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a_userauthapp/urls.py
from django.urls import path
from . import views

app_name = 'a_userauthapp'

urlpatterns = [
    path('login_view/', views.login_view, name='login'),
    path('logout_view/', views.logout_view, name='logout'),

    path('bulk-import-students/', views.bulk_import_students, name='bulk_import_students'),

    path('profile/', views.profile_view, name='student_profile'),  # Current user's profile
    path('profile/<path:matric_number>/', views.profile_view, name='student_profile_detail'),  # View another user's profile
    path('edit_profile/<path:matric_number>/', views.edit_profile, name='edit_profile'),

    path('student_room_complaint/', views.student_room_complaint, name='student_room_complaint'),
]

b_hostels/urls.py
from django.urls import path
from . import views

app_name = 'b_hostels'

urlpatterns = [
    path('manage_users_in_room/', views.admin_manage_users_in_room, name='admin_manage_users_in_room'),
    path('all-complaints/', views.all_complaints, name='all_complaints'),
]

templates/includes/footer.html
<!-- Footer -->
<footer class="bg-blue-800 text-white p-4 mt-6">
    <div class="container mx-auto text-center">
        <p>&copy; 2024 IUO Hostel Management System. All rights reserved.</p>
    </div>
</footer>

templates/includes/header.html
{% load static %}

<header x-data="{ mobilenavOpen: false }" class="md:flex items-center justify-between [&>*]:px-8 bg-blue-900 h-20 text-white sticky top-0 z-40">
    <div class="flex items-center justify-between h-20">
        <logo>
            <a class="flex items-center gap-1" href="{% url 'home' %}">
                <img class="w-7 -mt-1" src="{% static 'images/logo2.png' %}"/>
                <span class="text-lg font-bold">IUO-Hostel Management System</span>
            </a>
        </logo>
        <mobileicon class="md:hidden">
            <a @click="mobilenavOpen = !mobilenavOpen" class="h-12 w-12 flex items-center justify-center cursor-pointer hover:bg-gray-700 rounded-lg">
                <img x-show="!mobilenavOpen" class="w-6 h-6 select-none" src="https://img.icons8.com/small/64/ffffff/menu.png"/> 
                <img x-show="mobilenavOpen" x-cloak class="w-6 h-6 select-none" src="https://img.icons8.com/small/64/ffffff/delete-sign.png"/>
            </a>
        </mobileicon>
    </div>
    <nav x-show="mobilenavOpen" x-cloak class="md:!block bg-blue-900 h-screen w-screen md:h-auto md:w-auto -mt-20 md:mt-0 absolute md:relative z-[-1]"
    x-transition:enter="duration-300 ease-out"
    x-transition:enter-start="opacity-0 -translate-y-96"
    x-transition:enter-end="opacity-100 translate-y-0">
        <ul class="flex items-center navitems flex-col md:flex-row gap-8 md:gap-0 justify-center h-full -translate-y-10 md:translate-y-0">
            
            {% if user.is_authenticated %}
                {% if user.is_superuser or user.is_staff %}
                <li>
                    <a href="{% url 'b_hostels:admin_manage_users_in_room' %}" 
                       class="block px-4 py-2 hover:bg-blue-500 hover:text-white">
                        <i class="fas fa-user-cog mr-2"></i> Hostel Admin
                    </a>
                </li>                
                {% endif %}
            {% endif %}

            <li x-data="{ dropdownOpen: false }" class="relative">
                <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false" class="cursor-pointer select-none">

                    {% if user.is_authenticated %}

                    {% if profile.user.image %}
                    <img src="{{ profile.user.image }}" alt="Profile Picture" class="w-12 h-12 rounded-full object-cover border-2 border-blue-500 shadow">
                    {% else %}
                    <img src="{% static 'images/default-profilepic.png' %}" alt="Profile Picture" class="w-12 h-12 rounded-full object-cover border-2 border-blue-500 shadow">
                    {% endif %}

                        {{ user.first_name|title }} {{ user.last_name|title }}
                        <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4" src="https://img.icons8.com/small/32/777777/expand-arrow.png"/>
                    {% else %}
                        <img class="h-12 w-12 rounded-full object-cover" src="{% static 'images/default-profilepic.png' %}" alt="profile-image"/>
                        student
                        <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4" src="https://img.icons8.com/small/32/777777/expand-arrow.png"/>
                    {% endif %}
                </a>
                <div x-show="dropdownOpen" x-cloak class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                x-transition:enter="duration-300 ease-out"
                x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                x-transition:enter-end="opacity-100 translate-y-0 scale-100">
                    <ul class="hoverlist [&>li>a]:justify-center">
                        
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'a_userauthapp:student_profile' %}">My Profile</a></li>
                            <li><a href="{% url 'a_userauthapp:logout' %}">Log Out</a></li>
                        {% else %}
                            <li><a href="{% url 'a_userauthapp:login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </li>
        </ul>
    </nav>
</header>

templates/includes/home-hero.html
{% load static %}

<hero class="grid bg-gray-700 text-white text-center bg-cover z-10 relative" class="grid bg-gray-800 text-white text-center z-10 relative" 
    style="background-image: url('{% static 'images/hero1.jpg' %}'); background-size: auto; background-position: center; background-repeat: repeat;">
    <div class="col-start-1 row-start-1 bg-gray-800 bg-opacity-40 w-full h-full"></div>
    <div class="col-start-1 row-start-1 py-24 px-10 ">      
        
    </div>
</hero>

templates/includes/layout_a.html
{% extends 'HMS/base.html' %}

{% block layout %}
    {% include 'includes/home-hero.html' %}
    <content class="block  mx-auto mt-12 mb-20 px-6">

        {% block content %}


        {% endblock %}

    </content>
{% endblock %}

templates/includes/layout_b.html
{% extends 'HMS/base.html' %}

{% block layout %}

<content class="block max-w-3xl mx-auto my-12 px-6">
    <div class="card p-8 !pb-10">
        {% block content %}

        {% endblock %}
    </div>
</content>

{% endblock %}

templates/includes/messages.html
{% if messages %}
<div x-data="{ showMessage: false }" >
    {% for message in messages %}
    <div x-cloak class="absolute mx-auto left-0 right-0 mt-2 max-w-xl z-50 flex items-center 
                {% if message.tags == 'error' %}bg-red-500{% else %}bg-green-700{% endif %} text-white p-3 rounded-lg" role="alert"
        x-show="showMessage" 
        x-init="setTimeout(() => showMessage = true, 200), setTimeout(() => showMessage = false, 6000)"
        x-transition:enter="duration-700 ease-out"
        x-transition:enter-start="opacity-0 -translate-y-5"
        x-transition:enter-end="opacity-100 translate-y-0"
        x-transition:leave="duration-200 ease-in"
        x-transition:leave-start="opacity-100 translate-y-0"
        x-transition:leave-end="opacity-0 -translate-y-5">
            <svg class="w-8 h-8 mr-2"  viewBox="0 0 512 512">
                <path d="M315.27,33,96,304H224L192.49,477.23a2.36,2.36,0,0,0,2.33,2.77h0a2.36,2.36,0,0,0,1.89-.95L416,208H288L319.66,34.75A2.45,2.45,0,0,0,317.22,32h0A2.42,2.42,0,0,0,315.27,33Z" style="fill:none;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px" fill="white"></path>
            </svg>
            <div>
                <div class="text-lg">{{ message }}</div>
            </div>
            <div class="ml-auto cursor-pointer" @click="showMessage = false">
                <svg fill="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 ml-2">
                    <path d="M6 18L18 6M6 6l12 12"></path>
                </svg>
            </div>
        </div> 
    {% endfor %}
</div>
{% endif %}